import { Wallet, TrendingUp } from "lucide-react";
import { useApi } from "@/lib/api";
import { useSession } from "@/lib/session";
import { formatCurrency, formatMonth } from "@/lib/format";
import type { Payslip, WithUser } from "@/lib/types";
import { StatCard } from "@/components/stat-card";
import { PageState } from "@/components/page-state";
import { PayslipTable } from "@/components/payroll/payslip-table";
import { PayrollAdminTable } from "@/components/payroll/payroll-admin-table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export function PayrollPage() {
  const { user } = useSession();
  const isAdmin = user.role === "ADMIN";
  const mine = useApi<{ payslips: Payslip[] }>("/api/payroll");
  const team = useApi<{ payslips: WithUser<Payslip>[] }>(isAdmin ? "/api/payroll?scope=all" : null);

  const latest = mine.data?.payslips[0];

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Payroll</h1>
        <p className="mt-1 text-muted-foreground">
          Review your monthly payslips and salary breakdown.
        </p>
      </div>

      {!mine.data || (isAdmin && !team.data) ? (
        <PageState error={mine.error ?? team.error} />
      ) : (
        <>
          {latest && (
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <StatCard
                icon={Wallet}
                label={`Latest net pay (${formatMonth(latest.month)})`}
                value={formatCurrency(latest.netPay)}
                hint={`Basic ${formatCurrency(latest.basicSalary)} + allowances ${formatCurrency(latest.allowances)}`}
              />
              <StatCard
                icon={TrendingUp}
                label="Payslips on record"
                value={String(mine.data.payslips.length)}
                hint="Generated by HR each month"
              />
            </div>
          )}

          {isAdmin && team.data ? (
            <Tabs defaultValue="mine">
              <TabsList>
                <TabsTrigger value="mine">My Payroll</TabsTrigger>
                <TabsTrigger value="team">All Employees</TabsTrigger>
              </TabsList>
              <TabsContent value="mine" className="mt-4">
                <PayslipTable payslips={mine.data.payslips} />
              </TabsContent>
              <TabsContent value="team" className="mt-4">
                <PayrollAdminTable payslips={team.data.payslips} />
              </TabsContent>
            </Tabs>
          ) : (
            <PayslipTable payslips={mine.data.payslips} />
          )}
        </>
      )}
    </div>
  );
}
